name: 🐛 Bug Report
description: File a bug report to help us improve.
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
  - hesprs # Your GitHub username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        **Please read our [Contributing Guidelines](./CONTRIBUTING.md) before proceeding.**

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you experiencing this issue?
      options:
        - Browser (Chrome/Firefox/Safari)
        - Node.js
        - Bun
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of our software are you running?
      placeholder: e.g., 1.0.2
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
